### ISSUE TITLE
[Bug] Latest update causes crash upon installation

### ISSUE THREAD

**Issue by b-risk** [stefancruz/GrayjayDailymotion#1]
When it asked to update the source it says I should review the new permissions, upon following it's instruction to reinstall the source the app crashes at 25%. Tried uninstalling and reinstalling it and it does the same thing. I am using a Pixel 6a on GrapheneOS 14.

**Comment by stefancruz** [comment]
Hi, there was an issue with that last update. I'm reverting it.

**Comment by stefancruz** [comment]
@b-risk, should be fixed now, 
I'm having some issues with the signature so I had to remove it for now.
