### ISSUE TITLE
Can't open channel

### ISSUE THREAD

**Issue by ThunderHen** [stefancruz/GrayjayDailymotion#2]
Hello i Can't open this channel https://www.dailymotion.com/Forbes_breaking_News I get the message no enabled source to support this channel.
By the way, I'm enjoying this plugin. Thank you for making it.

**Comment by stefancruz** [comment]
Hi there, thanks for the feedback. 
The version on the dev branch should fix it. There was an issue with the regular expression. 
I'll release it soon.

**Comment by stefancruz** [comment]
@ThunderHen  I just released a new version. It should work now, and the plugin should be faster.
Thanks for your patience. I had already detected and fixed the issue, but I wanted to test it a bit better. I also missed the notification for this issue.

**Comment by ThunderHen** [comment]
I tested the new update seems to fix the issue. Thank you so much for making this plugin.
